// This file is automatically generated. Do not change it manually.
import { z } from "zod";

export const UserRole = z.enum(["user", "admin"]);
export type UserRole = z.infer<typeof UserRole>;
export const UserCreateRequest = z
  .object({
    name: z.string().min(1).max(100),
    email: z.string().email(),
    age: z.number().int().gte(18).lte(120),
    role: UserRole.optional(),
  })
  .passthrough();
export type UserCreateRequest = z.infer<typeof UserCreateRequest>;
export const UserResponse = z
  .object({
    id: z.number().int(),
    name: z.string(),
    email: z.string(),
    age: z.number().int(),
    role: UserRole,
  })
  .passthrough();
export type UserResponse = z.infer<typeof UserResponse>;
export const ValidationError = z
  .object({
    loc: z.array(z.union([z.string(), z.number()])),
    msg: z.string(),
    type: z.string(),
  })
  .passthrough();
export type ValidationError = z.infer<typeof ValidationError>;
export const HTTPValidationError = z
  .object({ detail: z.array(ValidationError) })
  .partial()
  .passthrough();
export type HTTPValidationError = z.infer<typeof HTTPValidationError>;

export const schemas = {
  UserRole,
  UserCreateRequest,
  UserResponse,
  ValidationError,
  HTTPValidationError,
};
